### ISSUE TITLE
Automatización lavadora

### ISSUE THREAD

**Issue by ConsolaViejuna** [ConsolaViejuna/mkdocs-homeAssistantFacil#10]
Automatización de lavadora:

```
alias: Lavadora finalizada
description: Manda un aviso cuando la lavadora ha terminado
trigger:
  - below: '4'
    entity_id: sensor.bw_shp2_enchufe_power
    platform: numeric_state
condition:
  - condition: template
    value_template: '{{ trigger.from_state.state |int(-1) > trigger.to_state.state |int(0) }}'
action:
  - data:
      message: 🧺 La lavadora ha terminado
    service: notify.telegram_casa
  - data:
      entity_id: media_player.gh_todos
      message: La lavadora ha terminado su programa
    service: python_script.enviar_tts_media
  - delay: '00:00:30'
mode: single
```

**Comment by ConsolaViejuna** [comment]
```
- id: '1611617826606'
  alias: Lavadora Inicio
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.lavadora_current_consumption
    above: '10'
  condition:
  - condition: state
    entity_id: input_select.lavadora_status
    state: Apagado
  action:
  - service: input_select.select_option
    data:
      entity_id: imput_select.lavadora_status"
      option: Lavando
    entity_id: input_select.lavadora_status
  - service: tts.google_say
    data:
      entity_id: media_player.salon
      language: es
      message: La lavadora está en marcha, te avisaré cuando acabe, para que saques
        la ropa.
  mode: single
- id: '1611618424857'
  alias: Lavadora modo Espera
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.lavadora_current_consumption
    for: 00:02:00
    below: '2'
  condition:
  - condition: state
    entity_id: input_select.lavadora_status
    state: Lavando
  - condition: state
    entity_id: group.familia
    state: not_home
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.lavadora_status
      option: Espera
    entity_id: input_select.lavadora_status
  - service: notify.telegram_grupo
    data:
      message: 👚🧥💦 La lavadora ya ha terminado, pasará al modo de espera, cuando llegues
        a casa te lo recordaré
  mode: single
- id: '1611619172762'
  alias: Lavadora Fin de Espera
  description: ''
  trigger:
  - platform: state
    entity_id: person.javi_lopez_alarcon
    to: home
  - platform: state
    entity_id: person.esther_vidal
    to: home
  condition:
  - condition: state
    entity_id: input_select.lavadora_status
    state: Espera
  action:
  - service: input_select.select_option
    data:
      entity_id: imput_select.lavadora_status
      option: Finalizado
    entity_id: input_select.lavadora_status
  mode: single
- id: '1611619633715'
  alias: Lavadora Finalizado
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.lavadora_current_consumption
    for: 00:02:00
    below: '2'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: person.jaid: '1611617826606'
  alias: Lavadora Inicio
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.lavadora_current_consumption
    above: '10'
  condition:
  - condition: state
    entity_id: input_select.lavadora_status
    state: Apagado
  action:
  - service: input_select.select_option
    data:
      entity_id: imput_select.lavadora_status"
      option: Lavando
    entity_id: input_select.lavadora_status
  - service: tts.google_say
    data:
      entity_id: media_player.salon
      language: es
      message: La lavadora está en marcha, te avisaré cuando acabe, para que saques
        la ropa.
  mode: single
- id: '1611618424857'
  alias: Lavadora modo Espera
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.lavadora_current_consumption
    for: 00:02:00
    below: '2'
  condition:
  - condition: state
    entity_id: input_select.lavadora_status
    state: Lavando
  - condition: state
    entity_id: group.familia
    state: not_home
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.lavadora_status
      option: Espera
    entity_id: input_select.lavadora_status
  - service: notify.telegram_grupo
    data:
      message: 👚🧥💦 La lavadora ya ha terminado, pasará al modo de espera, cuando llegues
        a casa te lo recordaré
  mode: single
- id: '1611619172762'
  alias: Lavadora Fin de Espera
  description: ''
  trigger:
  - platform: state
    entity_id: person.javi_lopez_alarcon
    to: home
  - platform: state
    entity_id: person.esther_vidal
    to: home
  condition:
  - condition: state
    entity_id: input_select.lavadora_status
    state: Espera
  action:
  - service: input_select.select_option
    data:
      entity_id: imput_select.lavadora_status
      option: Finalizado
    entity_id: input_select.lavadora_status
  mode: single
- id: '1611619633715'
  alias: Lavadora Finalizado
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.lavadora_current_consumption
    for: 00:02:00
    below: '2'
  condition:
  - condition: or
    conditions:
    - condition: statevi_lopez_alarcon
      state: home
    - condition: state
      entity_id: person.esther_vidal
      state: home
  - condition: state
    entity_id: input_select.lavadora_status
    state: Lavando
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.lavadora_status
      option: Finalizado
    entity_id: input_select.lavadora_status
  mode: single
- id: '1611620171155'
  alias: Lavadora recordarorio
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.lavadora_status
    to: Finalizado
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.fin_lavadora
  condition: []
  action:
  - service: timer.start
    data:
      duration: '0'
    target:
      entity_id: timer.fin_lavadora
  - service: tts.google_say
    data:
      entity_id: media_player.salon
      language: es
      message: La lavadora ya terminó, debes poner la secadora, te lo recordaré cada
        15 minutos, hasta que me digas, ya he sacado la lavadora
  mode: single
```
