### ISSUE TITLE
Automatización para saber si un Shelly tiene actualización 

### ISSUE THREAD

**Issue by ConsolaViejuna** [ConsolaViejuna/mkdocs-homeAssistantFacil#39]
Crear automatización para saber si un Shelly tiene una actualización pendiente

- id: "9283742394"
  alias: Actualización Shelly disponible
  description:
    Avisa por Telegram cuando hay una actualización disponible para los
    dispositivos Shelly
  trigger:
    - platform: state
      entity_id: binary_sensor.persiana_estudio_firmware_update
      from: "off"
      to: "on"
  condition: []
  action:
    - service: notify.telegram_casa
      data:
        message: "💡 Actualización de firmware Shelly disponible: {{ trigger.to_state.attributes.latest_stable_version }}"
  mode: single

**Comment by ConsolaViejuna** [comment]
Directamente:
```
alias: Actualización Zigbee disponible
description: >-
  Avisa por Telegram cuando hay una actualización disponible para un dispositivo
  Zigbee
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/bridge/log
condition:
  - condition: template
    value_template: >-
      {{ trigger.payload_json.type == "ota_update" and
      trigger.payload_json.meta.status == "available"}}
action:
  - service: notify.telegram_casa
    data:
      message: >-
        📡 Actualización de firmware z2m disponible para {{
        trigger.payload_json.meta.device | replace("_","-") }}
mode: parallel
max: 25


```
