### ISSUE TITLE
Temperaturas maximas y minimas

### ISSUE THREAD

**Issue by javilopezalarcon** [ConsolaViejuna/mkdocs-homeAssistantFacil#9]
No te ha pasado nunca que te despiertas y dices, que frio… y te preguntas, cuanto abrá sido la temperatura minima?
Pues con statistics es facil. Creamos un sensor con los siguientes datos:

`  - platform: statistics
    entity_id: sensor.temperatura_bano
    max_age:
      hours: 24
    sampling_size: 600
    precision: 2
    name: stats_temperatura_bano
  - platform: template
    sensors:
      bano_temp_min:
        value_template: "{{ state_attr('sensor.stats_temperatura_bano', 'min_value') }}" 
      bano_temp_max:
         value_template: "{{ state_attr('sensor.stats_temperatura_bano', 'max_value') }}" 
   `

Esto hay que hacerlo por cada sensor que queramos crear y te dará 2 sensores, uno de maxima de las ultimas 24h y uno de minima de las ultimas 24 horas tambien.

**Comment by javilopezalarcon** [comment]
Luego con una tarjeta de Hacs como es multiple entity row, podemos hacer algo asi por ejemplo

![67FB29F7-86F2-4A39-9B62-4DF1A6CE5643](https://user-images.githubusercontent.com/77857755/141997612-5b3ec0ea-aeb2-453a-a351-b25888cca3b0.png)

Esta seria asi:

type: entities
entities:
  - entity: sensor.temperatura_media_casa
  - entity: sensor.temperatura_salon
    type: custom:multiple-entity-row
    name: Salon
    entities:
      - sensor.salon_temp_min
      - sensor.salon_temp_max
  - entity: sensor.temperatura_h_matrimonio
    type: custom:multiple-entity-row
    name: Matrimonio
    entities:
      - sensor.matrimonio_temp_min
      - sensor.matrimonio_temp_max
  - entity: sensor.temperatura_bano
    type: custom:multiple-entity-row
    name: Baño
    entities:
      - sensor.bano_temp_min
      - sensor.bano_temp_max
  - entity: sensor.temperatura_h_nenes
    type: custom:multiple-entity-row
    name: Nenes
    entities:
      - sensor.nenes_temp_min
      - sensor.nenes_temp_max
  - entity: sensor.temperatura_cocina
    type: custom:multiple-entity-row
    name: Cocina
    entities:
      - sensor.cocina_temp_min
      - sensor.cocina_temp_max
  - entity: sensor.temperatura_h_pc
    type: custom:multiple-entity-row
    name: Hab. Pc
    entities:
      - sensor.h_pc_temp_min
      - sensor.h_pc_temp_max
title: Temperaturas

**Comment by ConsolaViejuna** [comment]
```
- platform: statistics
    entity_id: sensor.temperatura_bano
    max_age:
      hours: 24
    sampling_size: 600
    precision: 2
    name: stats_temperatura_bano
  - platform: template
    sensors:
      bano_temp_min:
        value_template: "{{ state_attr('sensor.stats_temperatura_bano', 'min_value') }}" 
      bano_temp_max:
         value_template: "{{ state_attr('sensor.stats_temperatura_bano', 'max_value') }}"
```
